SELECT USER_ID, PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) AS cnt
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING cnt > 1
) AS sub
ORDER BY USER_ID ASC, PRODUCT_ID DESC;
